### ISSUE TITLE
Where to install?

### ISSUE THREAD

**Issue by huub-l** [Log1x/wp-smtp#2]
Hi,

Should I include `"log1x/wp-smtp": "^1.0"` in the Bedrock or theme composer file?

**Comment by Log1x** [comment]
Hi.

I know it's kind of a weird package for it, but it is for the theme composer.

I may re-write it in the near future.

**Comment by huub-l** [comment]
Got it working now, thanks!

**Comment by dlecan** [comment]
@huubl what is the « theme composer »?
My installation of the plugin doesn’t seem to work (see #5), may be my installation is wrong?!?

Thank you
