### ISSUE TITLE
Unable to find the "admin notice"

### ISSUE THREAD

**Issue by dlecan** [Log1x/wp-smtp#5]
> No admin menus or other bloat. Just a simple admin notice to verify your connection

In the README, I can read this, but I can't find anything in the admin dashboard after installing the plugin.
Where to find this "admin notice"?

I just did:
- `$ composer require log1x/wp-smtp`
- Configuration of environment variables `WP_SMTP*` (real env vars, not in `.env`)

Thank you

**Comment by huub-l** [comment]
Did you run $ composer require log1x/wp-smtp in the Sage directory? (Not the Bedrock) Then you should get an admin notice.

**Comment by dlecan** [comment]
Ok, I'm not using a Sage theme :rofl: I will change my strategy, thank you.
The README might be clearer about this need :smile:
