### ISSUE TITLE
Deprecated PHPMailer (WordPress 5.5.0)

### ISSUE THREAD

**Issue by Log1x** [Log1x/wp-smtp#6]
```php
Deprecated: class-phpmailer.php is deprecated since version 5.5.0! Use wp-includes/PHPMailer/PHPMailer.php instead. The PHPMailer class has been moved to wp-includes/PHPMailer subdirectory and now uses the PHPMailer\PHPMailer namespace. in /Users/brandon/Sites/example/site/web/wp/wp-includes/functions.php on line 5051
```

**Comment by tangrufus** [comment]
See: https://core.trac.wordpress.org/changeset/48033/

Maybe add `conflict` in `composer.json` if we bump WP requirement to >=5.5
See: https://github.com/ItinerisLtd/wp-phpmailer/pull/273/files

**Comment by Log1x** [comment]
this is actually really annoying and may warrant a rewrite as a mu-plugin so I don't have to require in the class files.

**Comment by jhhazelaar** [comment]
Hi, I've run into this problem to and created a pull request for a fix.

@Log1x I don't know if you want to rewrite this packages. But this fix will work for now. Thanks for creating this packages!
