### ISSUE TITLE
Compatible with Roots Radicle?

### ISSUE THREAD

**Issue by abombelli** [Log1x/wp-smtp#8]
I just installed the package in a Roots Radicle setup, but it does not work.
Is something specific needed in a Radicle environment?

**Comment by Log1x** [comment]
In the next week or so we will be releasing a much better SMTP/mail package specifically for Acorn and this package will be archived.

In the mean time, you can use https://discourse.roots.io/t/smtp-with-cloudways/26472/2 – updating to the package when it releases should be straight forward and only require adjusting the environment variable names used in that snippet.

**Comment by abombelli** [comment]
Great, thanks!
